USE [master]
GO

/****** Object:  Database [game_portal]    Script Date: 02.02.2024 г. 15:16:56 ******/
CREATE DATABASE [game_portal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'game_portal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\game_portal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'game_portal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\game_portal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [game_portal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [game_portal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [game_portal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [game_portal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [game_portal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [game_portal] SET ARITHABORT OFF 
GO

ALTER DATABASE [game_portal] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [game_portal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [game_portal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [game_portal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [game_portal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [game_portal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [game_portal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [game_portal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [game_portal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [game_portal] SET  ENABLE_BROKER 
GO

ALTER DATABASE [game_portal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [game_portal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [game_portal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [game_portal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [game_portal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [game_portal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [game_portal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [game_portal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [game_portal] SET  MULTI_USER 
GO

ALTER DATABASE [game_portal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [game_portal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [game_portal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [game_portal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [game_portal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [game_portal] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [game_portal] SET QUERY_STORE = OFF
GO

ALTER DATABASE [game_portal] SET  READ_WRITE 
GO

